language: node_js
sudo: false
node_js:
- '4'
# AWS Lambda
- '4.3.2'
- '6'
- '7'
- '8'
- '9'
- '10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - node-nan
